### ISSUE TITLE
TODO: Account for different cadences of Arctic/Antarctic magnetometers

### ISSUE THREAD

**Issue by KCollins** [KCollins/openspace-sonification-demos#4]
Robert and I are looking at files for the ground magnetometer demo. One of the issues: Arctic magnetometers collect data at a slower cadence than Antarctic magnetometers. How to approach this? 🤔 
We will try audifying a 17-20 day stretch around the Gannon Storm as a demo, and if that sounds good I'll try applying it to my high-speed jet data. 

 - [ ] Option 1: If your sonification system can handle playing multiple streams in one environment at different rates, then I will provide the .wav files as-is. The slower-cadence Arctic .wav files will be substantially shorter than the faster-cadence Antarctic .wav files for the same timespan. (This would also be a neat demo of that functionality, if it exists.) The Antarctic files are at a 50k samples/second; we would add a HPF to remove DC offset (35 Hz cutoff for audio; I have to backtrack to figure out what that would be for the instrument itself) and add a fade in/fade out. This would be pretty similar to what you get out of the existing CDAWeb audification (and that's what we'd use for our starting point.) 

 - [ ] (Option 1b: We include only the audification of the Antarctic magnetometers in our demo. Would much prefer to have both, but this would still be good. Doesn't get its own number because this is a subset of V1)

 - [ ] Option 2: We can slow down the Antarctic files so that they match in speed, and do a long-ish timespan. The Antarctic side of the globe will have better temporal resolution/texture, but that might be interesting to explore in itself. Sampling rate for this might be on the order of 4kS/sec - 17 days of data in about 5 seconds. (Might try rendering out 2, 4, 8 so we can listen to them independently)

 - [ ] Option 3: I can try a wavelet approach (similar to what's used in the HARP project) and try and match the speeds of the two halves.

 - [ ] Option 4: I can apply PaulXStretch to the Arctic files so that they match the Antarctic files in speed.
